<a href="https://colab.research.google.com/github/rijul27/Numpy/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [2]:
import numpy as np

In [45]:
l = [1,2,3,4,5,6]

In [46]:
arr = np.array(l)

In [47]:
arr

array([1, 2, 3, 4, 5, 6])

In [48]:
type(arr)

numpy.ndarray

In [49]:
np.array([[2,4],[8,9]])

array([[2, 4],
       [8, 9]])

In [50]:
# List to array method 2
np.asarray(l)

array([1, 2, 3, 4, 5, 6])

In [51]:
# List to array method 3
np.asanyarray(l)

array([1, 2, 3, 4, 5, 6])

In [52]:
# Matrix - subclass of array
b = np.matrix(l)

In [53]:
np.asanyarray(b) # It is showing matrix beacuse matrix it subclass of array

matrix([[1, 2, 3, 4, 5, 6]])

In [54]:
l1 = [1,2,3,4]

In [55]:
a = np.array(l1)

In [56]:
a

array([1, 2, 3, 4])

In [57]:
c = a # shallow copy

In [58]:
c

array([1, 2, 3, 4])

In [59]:
a

array([1, 2, 3, 4])

In [60]:
c[0] = 100

In [61]:
c

array([100,   2,   3,   4])

In [62]:
a # 100 comes in a also

array([100,   2,   3,   4])

In [63]:
d = np.copy(a) # deep copy

In [64]:
a[1] =  500

In [65]:
a

array([100, 500,   3,   4])

In [66]:
d # It remain as it is array([100,   2,   3,   4]) because of deep copy

array([100,   2,   3,   4])

In [68]:
# Creates an array by executing a function over each coordinate.
# In this case, it creates a 3x3 boolean array where elements are True if their row index equals their column index (diagonal elements).
np.fromfunction(lambda m,n: m==n, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [69]:
np.fromfunction(lambda m,n: m*n, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [70]:
np.fromfunction(lambda m,n: m+n, (3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [71]:
iterable = (i * i for i in range(5) )

In [72]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [73]:
np.fromstring('100 200', sep=' ')

array([100., 200.])

In [74]:
np.fromstring('20,45',sep=',')

array([20., 45.])

In [ ]:
#numpy DataTypes

In [75]:
l

[1, 2, 3, 4, 5, 6]

In [78]:
arr

array([1, 2, 3, 4, 5, 6])

In [80]:
# Returns the number of dimensions of the array.
arr.ndim

1

In [84]:
arr2  = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [85]:
arr2.ndim

2

In [86]:
arr2.size

10

In [87]:
arr2.shape

(2, 5)

In [89]:
arr.dtype

dtype('int64')

In [90]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [92]:
list(np.arange(2.3,5.6))

[np.float64(2.3), np.float64(3.3), np.float64(4.3), np.float64(5.3)]

In [93]:
list(np.arange(2.3,5.6,.3))

[np.float64(2.3),
 np.float64(2.5999999999999996),
 np.float64(2.8999999999999995),
 np.float64(3.1999999999999993),
 np.float64(3.499999999999999),
 np.float64(3.799999999999999),
 np.float64(4.099999999999999),
 np.float64(4.399999999999999),
 np.float64(4.699999999999998),
 np.float64(4.999999999999998),
 np.float64(5.299999999999998)]

In [95]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [96]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [98]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [101]:
arr3 = np.zeros((3,4,2)) # 3 dimension

In [102]:
arr3

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [103]:
arr3.ndim

3

In [105]:
arr4 = np.zeros((3,4,2,3)) # 4 dimension

In [106]:
arr4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [107]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [108]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [109]:
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [110]:
op = np.ones((2,4,5))

In [111]:
op + 10

array([[[11., 11., 11., 11., 11.],
        [11., 11., 11., 11., 11.],
        [11., 11., 11., 11., 11.],
        [11., 11., 11., 11., 11.]],

       [[11., 11., 11., 11., 11.],
        [11., 11., 11., 11., 11.],
        [11., 11., 11., 11., 11.],
        [11., 11., 11., 11., 11.]]])

In [112]:
op * 7

array([[[7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.]],

       [[7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.]]])

In [113]:
# Creates a 2-D array with ones on the diagonal and zeros elsewhere, often called an identity matrix.
# The argument '5' specifies that it will be a 5x5 matrix.
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
np.logspace(2,5,base=2)

array([ 4.        ,  4.17340372,  4.35432466,  4.54308869,  4.74003581,
        4.94552078,  5.15991371,  5.38360077,  5.61698488,  5.8604864 ,
        6.11454394,  6.37961511,  6.65617737,  6.94472885,  7.24578931,
        7.55990103,  7.88762977,  8.22956587,  8.58632521,  8.9585504 ,
        9.3469119 ,  9.75210923, 10.17487225, 10.61596243, 11.07617429,
       11.55633675, 12.05731471, 12.58001053, 13.1253657 , 13.69436252,
       14.28802588, 14.90742511, 15.55367586, 16.22794219, 16.93143859,
       17.66543222, 18.43124515, 19.23025679, 20.06390632, 20.93369534,
       21.84119052, 22.78802646, 23.77590863, 24.8066164 , 25.88200631,
       27.00401538, 28.17466459, 29.39606253, 30.67040921, 32.        ])

In [6]:
arr_random = np.random.randn(3,4)

In [7]:
arr_random

array([[-0.36755935, -1.03870335,  0.27656263,  0.36370442],
       [-0.83104937,  0.78455781, -0.00814446,  0.17784322],
       [-1.20702211,  1.54267239,  0.41880511,  0.2616445 ]])

In [8]:
import pandas as pd

In [9]:
pd.DataFrame(arr_random)

          0         1         2         3
0 -0.367559 -1.038703  0.276563  0.363704
1 -0.831049  0.784558 -0.008144  0.177843
2 -1.207022  1.542672  0.418805  0.261645

In [5]:
np.random.rand(3,4)

array([[0.67220057, 0.52321326, 0.44160679, 0.13656332],
       [0.8280096 , 0.18064906, 0.67203585, 0.91782192],
       [0.24755651, 0.24225968, 0.79330996, 0.05343341]])

In [11]:
np.random.randint(1,100,(300,400))

array([[81, 57, 54, ..., 59, 14, 65],
       [ 3, 31, 68, ...,  3, 67, 37],
       [15, 38, 47, ...,  8, 83,  5],
       ...,
       [ 2,  9, 94, ..., 50, 18, 35],
       [11, 56, 44, ..., 16,  6, 64],
       [58,  7, 23, ..., 63, 98, 69]])

In [12]:
pd.DataFrame(np.random.randint(1,100,(300,400)))

,0,1,2,3,4,5,6,7,8,9,...,390,391,392,393,394,395,396,397,398,399
0,86,1,89,11,24,57,91,69,99,91,...,25,22,96,47,3,88,5,36,14,39
1,82,55,26,25,15,21,26,28,5,73,...,37,91,11,24,92,33,83,24,66,78
2,99,8,70,8,10,10,97,56,57,93,...,47,9,37,97,56,9,51,78,37,12
3,9,31,44,31,12,79,36,79,70,90,...,27,80,58,41,86,93,14,28,41,62
4,64,79,93,46,81,37,8,21,7,51,...,26,17,78,40,60,63,14,54,70,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,84,24,34,6,27,62,15,95,67,6,...,97,83,87,80,37,36,89,31,22,52
296,90,8,20,7,67,60,92,22,41,26,...,36,17,90,1,88,99,66,66,8,73
297,32,60,62,2,53,64,99,67,3,66,...,24,94,33,50,19,64,97,65,6,35
298,22,16,74,63,17,80,44,64,81,18,...,76,39,93,84,7,12,66,82,38,73
299,21,18,98,2,82,44,93,13,35,47,...,66,53,7,24,26,40,55,58,32,48

In [13]:
ran_data = pd.DataFrame(np.random.randint(1,100,(300,400)))

In [14]:
ran_data.to_csv("Random_data.csv")

In [15]:
arr_rand = np.random.rand(3,4)

In [16]:
arr_rand

array([[0.46456985, 0.35009862, 0.29084672, 0.27859984],
       [0.52878575, 0.17594235, 0.13229738, 0.62433457],
       [0.66956325, 0.70378968, 0.15039137, 0.699806  ]])

In [17]:
arr_rand.size

12

In [18]:
arr_rand.shape

(3, 4)

In [19]:
arr_rand.reshape(4,3)

array([[0.46456985, 0.35009862, 0.29084672],
       [0.27859984, 0.52878575, 0.17594235],
       [0.13229738, 0.62433457, 0.66956325],
       [0.70378968, 0.15039137, 0.699806  ]])

In [20]:
arr_rand.reshape(2,6)

array([[0.46456985, 0.35009862, 0.29084672, 0.27859984, 0.52878575,
        0.17594235],
       [0.13229738, 0.62433457, 0.66956325, 0.70378968, 0.15039137,
        0.699806  ]])

In [22]:
l = [8,1,4,5,6]

In [25]:
a = np.array(l)

In [26]:
a

array([8, 1, 4, 5, 6])

In [27]:
a>5

array([ True, False, False, False,  True])

In [28]:
array1 = np.random.randint(1,4,(4,4))
array2 = np.random.randint(1,4,(4,4))

In [29]:
array1

array([[1, 2, 1, 1],
       [2, 3, 2, 1],
       [1, 2, 2, 2],
       [1, 3, 2, 1]])

In [30]:
array2

array([[1, 2, 2, 2],
       [3, 1, 1, 3],
       [1, 1, 1, 1],
       [3, 3, 2, 3]])

In [31]:
array1 + array2

array([[2, 4, 3, 3],
       [5, 4, 3, 4],
       [2, 3, 3, 3],
       [4, 6, 4, 4]])

In [32]:
array1 - array2

array([[ 0,  0, -1, -1],
       [-1,  2,  1, -2],
       [ 0,  1,  1,  1],
       [-2,  0,  0, -2]])

In [33]:
array1 * array2

array([[1, 4, 2, 2],
       [6, 3, 2, 3],
       [1, 2, 2, 2],
       [3, 9, 4, 3]])

In [34]:
#matrix multiplication using numpy
array1 @ array2

array([[11,  8,  7, 12],
       [16, 12, 11, 18],
       [15, 12, 10, 16],
       [15, 10,  9, 16]])

In [35]:
np.sqrt(array1)

array([[1.        , 1.41421356, 1.        , 1.        ],
       [1.41421356, 1.73205081, 1.41421356, 1.        ],
       [1.        , 1.41421356, 1.41421356, 1.41421356],
       [1.        , 1.73205081, 1.41421356, 1.        ]])

In [36]:
np.exp(array1)

array([[ 2.71828183,  7.3890561 ,  2.71828183,  2.71828183],
       [ 7.3890561 , 20.08553692,  7.3890561 ,  2.71828183],
       [ 2.71828183,  7.3890561 ,  7.3890561 ,  7.3890561 ],
       [ 2.71828183, 20.08553692,  7.3890561 ,  2.71828183]])

In [37]:
np.log10(array1)

array([[0.        , 0.30103   , 0.        , 0.        ],
       [0.30103   , 0.47712125, 0.30103   , 0.        ],
       [0.        , 0.30103   , 0.30103   , 0.30103   ],
       [0.        , 0.47712125, 0.30103   , 0.        ]])